---
- hosts: geek

  vars_files:
    - /home/ansible/roles/wordpress/vars/wordpress.yml
    - /home/ansible/roles/wordpress/vars/wordpress_vault.yml 
  roles:
    - { role: geerlingguy.nginx, tags: [nginx]}
    - { role: geerlingguy.php, tags: [php]}
    - { role: geerlingguy.mysql, tags: [mysql]}
    - { role: wordpress, tags: [wordpress, app]}

