- name: Install vim for RHEL
  import_tasks: redhat_vim.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install vim for Debian
  import_tasks: debian_vim.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install mc for RHEL
  import_tasks: redhat_mc.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install mc for Debian
  import_tasks: debian_mc.yml
  when: ansible_facts['os_family']|lower == 'debian'

